version: '3.4'

services:
  productsdb:
    container_name: productsdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=ProductsDb
    restart: always
    ports:
        - "5432:5432"
    networks:
      - Sakikku
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=msh2050@yahoo.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
        - "5050:80"
    networks:
      - Sakikku
    volumes:
      - pgadmin_data:/root/.pgadmin

  products.api:
    container_name: products.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=productsdb;Username=admin;Port=5432;Password=admin1234;Database=ProductsDb;Pooling = true;
    restart: always
    ports:
      - "8000:80"
    depends_on:
      productsdb:
        condition: service_healthy
    networks:
      - Sakikku
      
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    networks:
      - Sakikku
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

